module.exports = {
    login: "mugan86",
    id: 5081970,
    node_id: "MDQ6VXNlcjUwODE5NzA=",
    avatar_url: "https://avatars0.githubusercontent.com/u/5081970?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/mugan86",
    html_url: "https://github.com/mugan86",
    followers_url: "https://api.github.com/users/mugan86/followers",
    following_url: "https://api.github.com/users/mugan86/following{/other_user}",
    gists_url: "https://api.github.com/users/mugan86/gists{/gist_id}",
    starred_url: "https://api.github.com/users/mugan86/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/mugan86/subscriptions",
    organizations_url: "https://api.github.com/users/mugan86/orgs",
    repos_url: "https://api.github.com/users/mugan86/repos",
    events_url: "https://api.github.com/users/mugan86/events{/privacy}",
    received_events_url: "https://api.github.com/users/mugan86/received_events",
    type: "User",
    site_admin: false,
    name: "Anartz Mugika Ledo",
    company: "@compodoc-course @npm-js-ts-angular-modules-course @graphql-course",
    blog: "https://anartz-mugika.com",
    location: "Soraluze (Basque Country) (EU)",
    email: null,
    hireable: true,
    bio: "[{#front [#mobile: {#android, #kotlin-java, #ionic}}, {#web: {#angular, #material, #bs}}], {#back: [{#graphql, #symfony,#express, #mongodb}]}] TG: anartz_naiz",
    twitter_username: "mugan86",
    public_repos: 132,
    public_gists: 210,
    followers: 85,
    following: 38,
    created_at: "2013-07-24T14:28:55Z",
    updated_at: "2020-11-30T15:38:16Z"
}