module.exports = {
    login: "Sebastian197",
    id: 38566816,
    node_id: "MDQ6VXNlcjM4NTY2ODE2",
    avatar_url: "https://avatars2.githubusercontent.com/u/38566816?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Sebastian197",
    html_url: "https://github.com/Sebastian197",
    followers_url: "https://api.github.com/users/Sebastian197/followers",
    following_url: "https://api.github.com/users/Sebastian197/following{/other_user}",
    gists_url: "https://api.github.com/users/Sebastian197/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Sebastian197/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Sebastian197/subscriptions",
    organizations_url: "https://api.github.com/users/Sebastian197/orgs",
    repos_url: "https://api.github.com/users/Sebastian197/repos",
    events_url: "https://api.github.com/users/Sebastian197/events{/privacy}",
    received_events_url: "https://api.github.com/users/Sebastian197/received_events",
    type: "User",
    site_admin: false,
    name: "Chano",
    company: null,
    blog: "",
    location: "Telde, Las Palmas",
    email: null,
    hireable: null,
    bio: null,
    twitter_username: null,
    public_repos: 11,
    public_gists: 0,
    followers: 0,
    following: 0,
    created_at: "2018-04-20T16:23:24Z",
    updated_at: "2020-12-01T20:07:41Z"
}